
export const RIDE_SELECTED = 'RIDE_SELECTED'
export const FETCH_RIDES = 'FETCH_RIDES'
export const PREFERENCES_SELECTED = 'PREFERENCES_SELECTED'
export const FETCH_BOOK_STATE = 'FETCH_BOOK_STATE'
export const PAYMENT_OPTION_SELECTED = 'PAYMENT_OPTION_SELECTED'
export const MODAL_ACTIONS = 'MODAL_ACTIONS'