
export const RIDE_SELECTED = 'RIDE_SELECTED'
export const FETCH_RIDES = 'FETCH_RIDES'
export const PREFERENCES_SELECTED = 'PREFERENCES_SELECTED'
export const FETCH_BOOK_STATE = 'FETCH_BOOK_STATE'
export const PAYMENT_OPTION_SELECTED = 'PAYMENT_OPTION_SELECTED'
export const MODAL_ACTIONS = 'MODAL_ACTIONS'
export const FETCH_ROUTES = 'FETCH_ROUTES';
export const NOT_FOUND = 'NOT_FOUND'
export const RESET_LOADING_TO_TRUE = 'RESET_LOADING_TO_TRUE'
export const UPDATE_STATE = 'UPDATE_STATE'
export const MAX_DAY = 21
export const SEAT_SELECTED = 'SEAT_SELECTED'
export const INIT_SEATS = 'INIT_SEATS';
export const PROCESS_FORM = 'PROCESS_FORM'
export const ERROR_PROCESSING_TRIP = 'ERROR_PROCESSING_TRIP';
export const SUCCESS_PROCESS_TRIP = 'SUCCESS_PROCESS_TRIP';